config/routes.rb
Rails.application.routes.draw do
  
  resources :user_data
  resources :transactions
  resources :products
  get 'index.html'  => "sites#index"
  get '/about'      => "sites#about"
  get 'sites/support'
  post '/sites' => "sites#save_announcement"

  get '/offers' => "sites#offers"

  get '/new/admin.html' => "users#admin_new"
  get 'balance.info'    => "users#balance"
  get "/users/:id/view" => "users#view"
  get 'logout.do'	=> "sessions#destroy", :as => "logout"
  get 'login.do'	=> "sessions#create", :as => "login"
  get 'signin'  => "sessions#create", :as => "signin"
  
  #delete record
  get '/:id/delete' => "users#destroy"

  get 'signup.php'	=> "users#new", :as => "signup"
  get '/:id/view'	=> "users#view"

  get '/new/promos' => "users#new_promo"
  post '/new/promos' => "users#create_promo"

  get '/new/announcement.html' => "sites#a_new"
  post '/new/queue' => "users#report"
  get '/dashboard'	=> "users#main"
  root :to => "sites#index"
  


  
  resources :users
  resources :sessions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_data_controller.rb
class UserDataController < ApplicationController
  before_action :set_user_datum, only: [:show, :edit, :update, :destroy]

  # GET /user_data
  # GET /user_data.json
  def index
    @user_data = UserDatum.all
  end

  # GET /user_data/1
  # GET /user_data/1.json
  def show
  end

  # GET /user_data/new
  def new
    @user_datum = UserDatum.new
  end

  # GET /user_data/1/edit
  def edit
  end

  # POST /user_data
  # POST /user_data.json
  def create
    @user_datum = UserDatum.new(user_datum_params)

    respond_to do |format|
      if @user_datum.save
        format.html { redirect_to @user_datum, notice: 'User datum was successfully created.' }
        format.json { render :show, status: :created, location: @user_datum }
      else
        format.html { render :new }
        format.json { render json: @user_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_data/1
  # PATCH/PUT /user_data/1.json
  def update
    respond_to do |format|
      if @user_datum.update(user_datum_params)
        format.html { redirect_to @user_datum, notice: 'User datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_datum }
      else
        format.html { render :edit }
        format.json { render json: @user_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_data/1
  # DELETE /user_data/1.json
  def destroy
    @user_datum.destroy
    respond_to do |format|
      format.html { redirect_to user_data_url, notice: 'User datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_datum
      @user_datum = UserDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_datum_params
      params.require(:user_datum).permit(:age, :address, :email_address, :contact_number, :user_id)
    end
end

app/helpers/user_data_helper.rb
module UserDataHelper
end

app/views/user_data/_form.html.erb
<%= form_for(user_datum) do |f| %>
  <% if user_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_datum.errors.count, "error") %> prohibited this user_datum from being saved:</h2>

      <ul>
      <% user_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>

  <div class="field">
    <%= f.label :contact_number %>
    <%= f.text_field :contact_number %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_data/edit.html.erb
<h1>Editing User Datum</h1>

<%= render 'form', user_datum: @user_datum %>

<%= link_to 'Show', @user_datum %> |
<%= link_to 'Back', user_data_path %>

app/views/user_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Data</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Address</th>
      <th>Email address</th>
      <th>Contact number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_data.each do |user_datum| %>
      <tr>
        <td><%= user_datum.age %></td>
        <td><%= user_datum.address %></td>
        <td><%= user_datum.email_address %></td>
        <td><%= user_datum.contact_number %></td>
        <td><%= user_datum.user_id %></td>
        <td><%= link_to 'Show', user_datum %></td>
        <td><%= link_to 'Edit', edit_user_datum_path(user_datum) %></td>
        <td><%= link_to 'Destroy', user_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Datum', new_user_datum_path %>

app/views/user_data/new.html.erb
<h1>New User Datum</h1>

<%= render 'form', user_datum: @user_datum %>

<%= link_to 'Back', user_data_path %>

app/views/user_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @user_datum.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_datum.address %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user_datum.email_address %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @user_datum.contact_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_datum.user_id %>
</p>

<%= link_to 'Edit', edit_user_datum_path(@user_datum) %> |
<%= link_to 'Back', user_data_path %>