config/routes.rb
Rails.application.routes.draw do
  
  resources :user_data
  resources :transactions
  resources :products
  get 'index.html'  => "sites#index"
  get '/about'      => "sites#about"
  get 'sites/support'
  post '/sites' => "sites#save_announcement"

  get '/offers' => "sites#offers"

  get '/new/admin.html' => "users#admin_new"
  get 'balance.info'    => "users#balance"
  get "/users/:id/view" => "users#view"
  get 'logout.do'	=> "sessions#destroy", :as => "logout"
  get 'login.do'	=> "sessions#create", :as => "login"
  get 'signin'  => "sessions#create", :as => "signin"
  
  #delete record
  get '/:id/delete' => "users#destroy"

  get 'signup.php'	=> "users#new", :as => "signup"
  get '/:id/view'	=> "users#view"

  get '/new/promos' => "users#new_promo"
  post '/new/promos' => "users#create_promo"

  get '/new/announcement.html' => "sites#a_new"
  post '/new/queue' => "users#report"
  get '/dashboard'	=> "users#main"
  root :to => "sites#index"
  


  
  resources :users
  resources :sessions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transactions = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:product_code, :phone_number, :quantity, :other)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_code %>
    <%= f.text_field :product_code %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :other %>
    <%= f.text_field :other %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "container" align="center">
<h1>Transactions</h1>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th>Product code</th>
      <th>Phone number</th>
      <th>Quantity</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.product_code %></td>
        <td><%= transaction.phone_number %></td>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.other %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product code:</strong>
  <%= @transaction.product_code %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @transaction.phone_number %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Other:</strong>
  <%= @transaction.other %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

<% @transactions.each do |f| %>
  <div class="row">
    <div class="col-md-3" style="background-color:yellow;"><%= f.product_code %></div>
    <div class="col-md-3" style="background-color:red;"><%= f.phone_number %></div>
    <div class="col-md-3" style="background-color:blue;"><%= f.quantity %></div>
    <div class="col-md-3" style="background-color:gray;"><%= f.other %></div>
  </div>
<% end %>